# This is a config for E2B sandbox template.
# You can use template ID (ziksdofsuxuq20ijo96k) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("ziksdofsuxuq20ijo96k") # Sync sandbox
# sandbox = await AsyncSandbox.create("ziksdofsuxuq20ijo96k") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ziksdofsuxuq20ijo96k')

team_id = "e29b1787-a33d-4ba7-b7c7-86ecee020da9"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "ziksdofsuxuq20ijo96k"
